version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
  mongo:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: skillsync
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
